AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.pkg.lambdaone::lambda2
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Lambda2VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.32.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: false
      InstanceTenancy: default

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref Lambda2VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: 172.32.0.0/16
      MapPublicIpOnLaunch: true

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "sec-grp-lambda2"
      GroupDescription: "Security group for lambda2"
      VpcId: !Ref Lambda2VPC

  Lambda2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.pkg.lambdaone.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/lambda2-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 90
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2

Outputs:
  Lambda1Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Lambda2Api
