AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.pkg.lambdaone::lambda1
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  Lambda1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.pkg.lambdaone.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/lambda1-1.0-SNAPSHOT.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Policies:
        - Statement: 
          - Sid: ExecuteLambda2
            Effect: Allow
            Action: 
            - lambda:InvokeFunction
            Resource: '*' 
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  Lambda1Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: Lambda1Api
